name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs: 
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run eslint
      - run: npm run build
      - run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Trigger deployment
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        if: ${{ github.event_name == 'push' && !contains(join(env.COMMIT_MESSAGES), 'skip') }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - uses: rjstone/discord-webhook-notify@v1
        if: ${{ success() && github.event_name == 'push' && !contains(join(env.COMMIT_MESSAGES), 'skip') }}
        with:
          severity: info
          color: '#ffffff'
          text: 'A new version deployed'
          description: 'https://full-stack-open-pokedex-a21x.onrender.com/'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          COMMITTER: ${{ toJson(github.event.commits[0].committer.username) }}
          URL: ${{ toJson(github.event.commits[0].url)}}
        if: ${{ github.event_name == 'push' && !contains(join(env.COMMIT_MESSAGES), 'skip') }}
        uses: anothrNick/github-tag-action@1.64.0
      - uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() }}
        with:
          severity: error
          color: '#000000'
          text: 'Build failed'
          description: env.URL
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      
        
        


          